[package]
name = "gbi"
version = "0.1.4"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
crossterm = "0.29.0"
git2 = "0.20.3"
ratatui = "0.20.0"
openssl = { version = "0.10", features = ["vendored"] }
